### ISSUE TITLE
Problem with overleaf - Restricted, sorry you don't have permission to load this page.

### ISSUE THREAD

**Issue by kourouklides** [MauroCE/Dissertation#1]
Problem with overleaf link:

Restricted, sorry you don't have permission to load this page.

**Comment by MauroCE** [comment]
@kourouklides Thank you for letting me know! I've updated the README file to link to the file Dissertation.pdf, which is indeed the latest version of my Thesis. Also, if you're reading it, do you mind giving me some feedback?

Thanks!

**Comment by sabbatgillani** [comment]
I am facing the same problem and I had a project that was about to complete it and I haven't saved that file now I am out of my project. Please let me know how can I fix it. Otherwise, all of my time and effort will go for nothing.

**Comment by visirion07** [comment]
> I am facing the same problem and I had a project that was about to complete it and I haven't saved that file now I am out of my project. Please let me know how can I fix it. Otherwise, all of my time and effort will go for nothing.

The same happened with me too. Did you get any solution?

**Comment by fsqy-zhang** [comment]
> > 我遇到了同样的问题，我有一个即将完成的项目，但我没有保存该文件，现在我已经退出了我的项目。请让我知道我该如何解决。否则，我所有的时间和精力都将付诸东流。
> 
> 我也发生了同样的事情。您得到任何解决方案了吗？

请问您后面又解决方案吗
